# Default language to use for running CI
language: python

# Sudo false allows Travis CI to run in a containerized environment (Docker)
# rather than a full VM
sudo: false

# Specifies the linux distribution to run the CI on
dist: trusty

# Testing matrix for any environment variables or specific versions
# of testing environments
matrix:
  fast_finish: true
  include:
  # TODO: Uncomment when test is ready
  # - python: 3.6
  #   env: TEST_TARGET=test
  - python: 3.6
    env: TEST_TARGET=lint

# Download of any lower level dependencies to install the software
before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - ./infra/scripts/setup-server.sh

# Install our software
install:
  - echo 'Install package here...'

# Script to run any sort of testing, deployments, linting, etc
script:
  - ./infra/scripts/test.sh
  - ./infra/scripts/lint.sh
