# Default language to use for running CI
language: python

# Sudo false allows Travis CI to run in a containerized environment (Docker)
# rather than a full VM
sudo: false

# Specifies the linux distribution to run the CI on
dist: trusty

services:
  - postgresql


# Testing matrix for any environment variables or specific versions
# of testing environments
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
      - POSTGRES_NAME=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost

# Download of any lower level dependencies to install the software
before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - ./infra/scripts/setup-server.sh

# Install our software
before_script:
  - psql -c "create database ${POSTGRES_NAME};" -U ${POSTGRES_USER}

# Script to run any sort of testing, deployments, linting, etc
script:
  - ./infra/scripts/test.sh
  - ./infra/scripts/lint.sh
